# declare variables
variable "vpc_cidr_block" {}
variable "first_az" {}
variable "second_az" {}
variable "instance_type" {}
variable "key_pair_name" {}
variable "enviroment" {}
variable "subnet_1_cidr" {}
variable "subnet_2_cidr" {}
variable "subnet_3_cidr" {}
variable "subnet_4_cidr" {}
variable "db_user_name" {}
variable "db_password" {}